### ISSUE TITLE
Show RIH functionality

### ISSUE THREAD

**Issue by beefoo** [NYPL-discovery/discovery-designs#9]
Functionality taken from slides 3-5 of [this document](https://docs.google.com/presentation/d/1f_pASMXhN0M3abByCIzi1mpz5VRpnqOnlMQrWwzAY58/edit#slide=id.g13616b8d9c_4_30)

**bold** indicates representation in wireframes
_italic_ indicates N/A for wireframes
## Check item status:
1. Case: no holds allowed on an item
2. Case: need special permission to access item
3. **Total # of copies of item**
4. **Current # of holds on a item**
5. **An estimate of the date/time (nearest hour) by which the item could be delivered**
6. **Check the building-level locations to which delivery is allowed**
   - Phase 1: limit displayed delivery choices to home library.
   - Phase 2: roll out intralibrary delivery, display only research branches
7. **Check the room-level locations to which delivery is allowed (mostly applicable to SASB)**
## Place hold
1. **Select the "on or after" date when the item will be delivered**
2. **Select the room-level location to which the item will be delivered (mostly applicable to SASB)**
3. **Indicate a date after which the request should be cancelled if not filled**
4. Indicate that I am currently on site to expedite the request
   - option available only during specific library hours
   - Sierra prioritizes holds only by timestamp when hold was placed)
## Get initial confirmation
1. _Receive an email confirmation that my request has been received_
2. _View the building and room pickup location in the email confirmation_
3. _View directions to the pickup location in the email confirmation_
4. _View the date of delivery in the email confirmation_
## Check hold status
1. **Check to see if a hold is available**
2. **View my position in the holds queue**
3. **View an estimated delivery date for a hold**
4. **View the delivery location of a hold**
## Manage hold
1. **Cancel a hold**
2. **Change the "cancel if not filled by" date for a hold**
3. **Change the room-level delivery location of a hold**
4. **Change the "on or after" date when the item will be delivered**
5. Suspend or freeze the hold (keep the hold last in queue until reactivated)
## Pick up
1. _Receive an email confirmation that my request has arrived_
2. _View the building and room pickup location in the email confirmation_
3. _View directions to the pickup location in the email confirmation_

**Comment by beefoo** [comment]
@thisismattmiller can you add the link to the relevant RIH docs?

**Comment by 0ara0** [comment]
Hey Brian -

Slides 3-5 here: https://docs.google.com/presentation/d/1f_pASMXhN0M3abByCIzi1mpz5VRpnqOnlMQrWwzAY58/edit#slide=id.g13616b8d9c_5_0

**Comment by beefoo** [comment]
@0ara0 thanks I updated the body to reflect the slides. Are there any in particular that should be prioritized to be reflected in the wireframes?

**Comment by beefoo** [comment]
Also, in **View my position in the holds queue**. Does that imply I can place a hold on an item even when there is already a hold placed on an item?

**Comment by 0ara0** [comment]
Re: View my position in the holds queue - yes. I don't know if that'll make it into the MVP but that is a desire.

**Comment by thisismattmiller** [comment]
Yeah, it is a very branch oriented feature because things are only "checked out" into the reading rooms for a few hours, so you would not be on a hold list really. But it is possible, and they might have some circ material checked out that I would assume would show up in their patron page.

**Comment by 0ara0** [comment]
Re: priorities, not sure but I'd say the only one that's obvious to me would likely not be a priority: 

2.2 - Indicate a date after which the request should be cancelled if not filled (5)

**Comment by 0ara0** [comment]
Well, they can also be placed on the hold shelf for up to 10 days, or in the case of 900K ReCAP items and MarLI items - even longer. I think these are the cases they had in mind.

This is still being clarified but there's also the idea of a hold reservation system, like a hotel room reservation: someone can reserve an item for Oct 8th, another can reserve the same item for today, etc. Not really relevant for the wireframes but just highlighting now as an FYI.

**Comment by beefoo** [comment]
Thanks, also **Case: need special permission to access item**, what's the current process for this and how it will be reflected in the system?  E.g. if they are filling out a paper form now, are we building that functionality online?
